"""
translate_latex.py — PT-BR → EN-US LaTeX translation
Uses GitHub Models API (free, GITHUB_TOKEN already available in Actions).
Only re-translates files whose content hash changed since the last run.

Real project structure:
    docs/project/
        shared/   ← page.sty, portland.sty, refs.bib, thesis_pack.tex, fig/
        pt/       ← source of truth (cover.tex, project_main.tex, cap*.tex …)
        en/       ← generated by this script

Usage:
    python scripts/translate_latex.py              # translate changed files only
    python scripts/translate_latex.py --force      # re-translate everything
    python scripts/translate_latex.py --dry-run    # show what would run, no API calls
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
from pathlib import Path

from openai import OpenAI

# ---------------------------------------------------------------------------
# Paths  (all relative to repo root)
# ---------------------------------------------------------------------------

REPO_ROOT  = Path(__file__).resolve().parent.parent
PT_DIR     = REPO_ROOT / "docs" / "project" / "pt"
EN_DIR     = REPO_ROOT / "docs" / "project" / "en"
SHARED_DIR = REPO_ROOT / "docs" / "project" / "shared"
CACHE_FILE = REPO_ROOT / "docs" / "project" / ".translation-cache.json"

# ---------------------------------------------------------------------------
# GitHub Models config
# ---------------------------------------------------------------------------

GITHUB_MODELS_BASE_URL = "https://models.github.ai/inference"
MODEL = "meta/llama-3.3-70b-instruct"   # free tier, "low" rate limit tier

# ---------------------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are an academic LaTeX translator specialising in engineering and computer science.
Translate the source file from Brazilian Portuguese to American English.

RULES — follow every one without exception:
1. Translate ONLY natural-language text: prose, section/chapter titles, captions,
   footnotes, abstracts, itemize/enumerate text.
2. NEVER modify LaTeX commands, environments, labels, refs, citations, or math.
   Examples of things you must NOT touch:
     \\chapter{Introdução}  →  \\chapter{Introduction}   ← translate only the brace content
     \\label{cap1}          →  leave exactly as-is
     \\cite{costa2024}      →  leave exactly as-is
     \\begin{equation}…     →  leave completely unchanged
     \\includegraphics{…}   →  leave completely unchanged
3. Preserve blank lines, indentation, and comment lines (% …).
4. Use formal academic register (IEEE / ACM style).
5. Return ONLY the translated LaTeX — no explanations, no markdown fences.\
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:20]


def load_cache() -> dict[str, str]:
    if CACHE_FILE.exists():
        return json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    return {}


def save_cache(cache: dict[str, str]) -> None:
    CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
    CACHE_FILE.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")


def translate(client: OpenAI, content: str) -> tuple[str, int, int]:
    """Returns (translated_text, input_tokens, output_tokens)."""
    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=8192,
        temperature=0.2,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": content},
        ],
    )
    usage = response.usage
    return (
        response.choices[0].message.content,
        usage.prompt_tokens if usage else 0,
        usage.completion_tokens if usage else 0,
    )


def ensure_symlinks(target_dir: Path) -> None:
    """
    Create symlinks inside target_dir pointing to everything in shared/.
    Both pt/ and en/ need these so that \\input{thesis_pack} resolves correctly
    without changing any paths inside the .tex files.

    Existing real files (e.g. cover.tex already in pt/) are never overwritten.
    """
    target_dir.mkdir(parents=True, exist_ok=True)

    for item in SHARED_DIR.iterdir():
        link = target_dir / item.name
        if link.exists() or link.is_symlink():
            continue  # already there — real file or existing symlink
        link.symlink_to(item.resolve())
        print(f"  symlink: {target_dir.name}/{item.name} → shared/{item.name}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Translate LaTeX PT-BR → EN-US")
    p.add_argument("--force",   action="store_true", help="Re-translate all files")
    p.add_argument("--dry-run", action="store_true", help="Show plan, no API calls")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    github_token = os.environ.get("GITHUB_TOKEN")
    if not github_token:
        print("ERROR: GITHUB_TOKEN not set.", file=sys.stderr)
        print("Locally: export GITHUB_TOKEN=<PAT with Models:Read scope>", file=sys.stderr)
        sys.exit(1)

    if not PT_DIR.exists():
        print(f"ERROR: PT source directory not found: {PT_DIR}", file=sys.stderr)
        sys.exit(1)

    if not SHARED_DIR.exists():
        print(f"ERROR: shared/ directory not found: {SHARED_DIR}", file=sys.stderr)
        sys.exit(1)

    # Symlinks so both pt/ and en/ can resolve \input{thesis_pack} etc.
    print("Setting up symlinks …")
    ensure_symlinks(PT_DIR)
    ensure_symlinks(EN_DIR)

    client = OpenAI(base_url=GITHUB_MODELS_BASE_URL, api_key=github_token)
    cache  = load_cache()

    # Decide which files to translate
    tex_files = sorted(PT_DIR.glob("*.tex"))
    if not tex_files:
        print(f"No .tex files found in {PT_DIR}")
        return

    to_translate: list[tuple[Path, Path, str, str]] = []

    for pt_file in tex_files:
        h       = file_hash(pt_file)
        en_file = EN_DIR / pt_file.name

        if not args.force and cache.get(pt_file.name) == h and en_file.exists():
            print(f"  ✓ unchanged : {pt_file.name}")
        else:
            reason = "forced" if args.force else ("new" if not en_file.exists() else "modified")
            to_translate.append((pt_file, en_file, h, reason))

    if not to_translate:
        print("\nAll files up-to-date. Nothing to translate.")
        return

    print(f"\n{len(to_translate)} file(s) to translate:")
    for pt_file, _, _, reason in to_translate:
        print(f"  → {pt_file.name}  ({reason})")

    if args.dry_run:
        print("\n[dry-run] Stopping before API calls.")
        return

    print()
    translated = 0
    total_in = 0
    total_out = 0
    for i, (pt_file, en_file, h, _) in enumerate(to_translate):
        print(f"  translating: {pt_file.name} …", end=" ", flush=True)
        try:
            result, tok_in, tok_out = translate(client, pt_file.read_text(encoding="utf-8"))
            en_file.write_text(result, encoding="utf-8")
            cache[pt_file.name] = h
            translated += 1
            total_in  += tok_in
            total_out += tok_out
            print(f"done  ({tok_in:,} in / {tok_out:,} out)")
        except Exception as exc:
            print(f"FAILED — {exc}", file=sys.stderr)
            # Don't update cache so it retries next run

        # GitHub Models free tier: 15 req/min  →  4 s between requests
        if i < len(to_translate) - 1:
            time.sleep(4)

    save_cache(cache)
    print(f"\n{translated}/{len(to_translate)} file(s) translated.")
    if total_in or total_out:
        print(f"Tokens used — input: {total_in:,}  output: {total_out:,}  total: {total_in + total_out:,}")
        # GitHub Models free tier daily limit: 170k tokens
        print(f"Free tier used: {(total_in + total_out) / 170_000 * 100:.1f}% of 170k daily limit")
    print(f"Cache: {CACHE_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()